"""Mutable train.py -- ALL experiments go here.

This is the ONLY file you may modify. prepare.py is frozen.
Claude Code iterates by editing this file directly: change models,
hyperparameters, feature engineering, ensembles, etc.

After each run, the workflow parses the JSON output from stdout
to decide keep (git commit) or revert (git checkout).

Generated by gsd-ml scaffold phase.
"""

import json
import joblib
import numpy as np
import pandas as pd
from pathlib import Path

# Classification models
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Regression models
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge

# Optional: XGBoost (TAB-01)
try:
    import xgboost as xgb
except ImportError:
    xgb = None

# Optional: LightGBM (TAB-01)
try:
    import lightgbm as lgb
except ImportError:
    lgb = None

# Import frozen data pipeline -- DO NOT MODIFY prepare.py
from prepare import load_data, split_data, build_preprocessor, evaluate

# --- Configuration (set by scaffold phase) ---
CSV_PATH = "__CSV_PATH__"
TARGET_COLUMN = "__TARGET_COLUMN__"
METRIC = "__METRIC__"
TASK = "__TASK__"  # "classification" or "regression"


def main():
    """Train and evaluate a model.

    Edit this function to try different models, hyperparameters,
    feature engineering, and ensembles. The workflow will run this
    file, parse the JSON output, and keep/revert based on results.
    """
    # Load and split data
    df = load_data(Path(CSV_PATH))
    X_train, X_test, y_train, y_test = split_data(df, TARGET_COLUMN)

    # Build preprocessor (handles numeric + categorical features)
    preprocessor = build_preprocessor(X_train)
    X_train_proc = preprocessor.fit_transform(X_train)
    X_test_proc = preprocessor.transform(X_test)

    # --- Choose and configure model ---
    if TASK == "classification":
        model = RandomForestClassifier(
            n_estimators=100,
            max_depth=10,
            random_state=42,
        )
    else:
        model = RandomForestRegressor(
            n_estimators=100,
            max_depth=10,
            random_state=42,
        )

    # --- Cross-validation evaluation (TAB-03) ---
    result = evaluate(model, X_train_proc, y_train, scoring=METRIC, task=TASK)
    cv_score = result["mean"]
    cv_std = result["std"]

    # --- Retrain on full training set and save artifacts ---
    model.fit(X_train_proc, y_train)
    preds = model.predict(X_test_proc)

    # Save predictions for diagnostics
    pd.DataFrame({"y_true": y_test, "y_pred": preds}).to_csv(
        "predictions.csv", index=False
    )

    # Save model for artifact export
    joblib.dump(model, "best_model.joblib")

    # --- Output JSON to stdout (MUST be the last print) ---
    print(json.dumps({"metric_value": cv_score, "metric_name": METRIC}))


if __name__ == "__main__":
    main()
