"""Mutable train.py -- ALL experiments go here.

This is the ONLY file you may modify. prepare.py is frozen.
Uses QLoRA (4-bit quantization) with LoRA adapters and SFTTrainer.

Claude Code iterates by editing this file directly: change LoRA params,
learning rate, epochs, etc.

After each run, the workflow parses the JSON output from stdout
to decide keep (git commit) or revert (git checkout).

Generated by gsd-ml scaffold phase.
"""

import json
import math
import os
from pathlib import Path

import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, TaskType, get_peft_model
from trl import SFTTrainer

from prepare import format_dataset, get_vram_info

# --- Configuration (set by scaffold phase) ---
MODEL_NAME = "__MODEL_NAME__"
LORA_R = __LORA_R__
LORA_ALPHA = __LORA_ALPHA__
METRIC = "__METRIC__"
MAX_LENGTH = __MAX_LENGTH__
BATCH_SIZE = __BATCH_SIZE__
LEARNING_RATE = __LEARNING_RATE__
NUM_EPOCHS = __NUM_EPOCHS__


def setup_quantization():
    """Configure 4-bit quantization for QLoRA."""
    return BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )


def setup_lora():
    """Configure LoRA adapter parameters."""
    return LoraConfig(
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules="all-linear",
        lora_dropout=0.05,
        task_type=TaskType.CAUSAL_LM,
    )


def evaluate_perplexity(model, tokenizer, eval_data):
    """Evaluate model perplexity on held-out eval set.

    Computes cross-entropy loss on each eval sample and returns
    perplexity as math.exp(average_loss).
    """
    model.eval()
    total_loss = 0.0
    count = 0

    with torch.no_grad():
        for item in eval_data:
            text = item["text"] if isinstance(item, dict) else str(item)
            inputs = tokenizer(
                text,
                return_tensors="pt",
                truncation=True,
                max_length=MAX_LENGTH,
            ).to(model.device)
            outputs = model(**inputs, labels=inputs["input_ids"])
            total_loss += outputs.loss.item()
            count += 1

    avg_loss = total_loss / max(count, 1)
    perplexity = math.exp(min(avg_loss, 700))
    return perplexity


def evaluate_rouge(model, tokenizer, eval_data):
    """Evaluate model with ROUGE metrics on held-out eval set.

    Generates predictions for each eval sample and computes
    ROUGE-1, ROUGE-2, and ROUGE-L scores.
    """
    import evaluate as hf_evaluate

    rouge = hf_evaluate.load("rouge")
    predictions = []
    references = []

    model.eval()
    for item in eval_data:
        original = item.get("original", {}) if isinstance(item, dict) else {}
        instruction = original.get("instruction", "")
        reference = original.get("output", "")

        inputs = tokenizer(
            instruction,
            return_tensors="pt",
            truncation=True,
            max_length=MAX_LENGTH,
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=256,
                do_sample=False,
            )

        prediction = tokenizer.decode(outputs[0], skip_special_tokens=True)
        predictions.append(prediction)
        references.append(reference)

    results = rouge.compute(predictions=predictions, references=references)
    return results


def main():
    """Run fine-tuning experiment."""
    # 1. Check VRAM and configure quantization
    vram_info = get_vram_info()
    print(f"Device: {vram_info['device']}, VRAM: {vram_info['vram_gb']}GB")

    quant_config = setup_quantization()

    # 2. Load model with quantization
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=quant_config,
        device_map="auto",
    )

    # 3. Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # 4. Apply LoRA
    lora_config = setup_lora()
    model = get_peft_model(model, lora_config)
    model.gradient_checkpointing_enable()
    model.print_trainable_parameters()

    # 5. Load and format dataset
    dataset = format_dataset(
        data_path="__DATA_PATH__",
        tokenizer_name=MODEL_NAME,
        max_length=MAX_LENGTH,
    )

    # 6. Training arguments
    training_args = TrainingArguments(
        output_dir="./output",
        per_device_train_batch_size=BATCH_SIZE,
        num_train_epochs=NUM_EPOCHS,
        learning_rate=LEARNING_RATE,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
        evaluation_strategy="epoch",
        report_to="none",
        gradient_accumulation_steps=4,
    )

    # 7. Create SFTTrainer
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset["train"],
        eval_dataset=dataset["eval"],
        processing_class=tokenizer,
    )

    # 8. Train
    trainer.train()

    # 9. Evaluate
    if METRIC == "perplexity":
        eval_metric = evaluate_perplexity(model, tokenizer, dataset["eval"])
        metric_name = "perplexity"
    elif METRIC.startswith("rouge"):
        rouge_results = evaluate_rouge(model, tokenizer, dataset["eval"])
        eval_metric = rouge_results.get(METRIC, rouge_results.get("rouge1", 0.0))
        metric_name = METRIC
    elif METRIC == "loss":
        eval_results = trainer.evaluate()
        eval_metric = eval_results["eval_loss"]
        metric_name = "loss"
    else:
        eval_metric = evaluate_perplexity(model, tokenizer, dataset["eval"])
        metric_name = "perplexity"

    # 10. Save adapter weights only
    model.save_pretrained("best_adapter")
    tokenizer.save_pretrained("best_adapter")

    # 11. Save predictions for diagnostics engine (loss-based metrics only)
    if METRIC in ("perplexity", "loss"):
        model.eval()
        all_losses = []
        with torch.no_grad():
            for item in dataset["eval"]:
                text = item["text"] if isinstance(item, dict) else str(item)
                inputs = tokenizer(
                    text, return_tensors="pt", truncation=True, max_length=MAX_LENGTH,
                ).to(model.device)
                outputs = model(**inputs, labels=inputs["input_ids"])
                all_losses.append(outputs.loss.item())

        import pandas as pd
        pd.DataFrame({"y_true": [0.0] * len(all_losses), "y_pred": all_losses}).to_csv("predictions.csv", index=False)

    # 12. Output result as JSON for engine parsing
    result = {"metric_name": metric_name, "metric_value": eval_metric}
    print(json.dumps(result))


if __name__ == "__main__":
    main()
