"""Mutable train.py -- ALL experiments go here.

This is the ONLY file you may modify. prepare.py is frozen.
Task: text_classification

Claude Code iterates by editing this file directly: change models,
hyperparameters, etc.

After each run, the workflow parses the JSON output from stdout
to decide keep (git commit) or revert (git checkout).

Generated by gsd-ml scaffold phase.
"""

import json
import time

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
from transformers import AutoModelForSequenceClassification

from prepare import get_device_info, load_text_data

# --- Configuration (set by scaffold phase) ---
TIME_BUDGET_SEC = __TIME_BUDGET_SEC__
PATIENCE = 5
MAX_EPOCHS = 100
METRIC_NAME = "__METRIC__"
DATA_PATH = "__DATA_PATH__"
MODEL_NAME = "__MODEL_NAME__"
BATCH_SIZE = __BATCH_SIZE__


def train():
    """Run time-budgeted training with early stopping and gradient clipping."""
    start = time.time()
    device_info = get_device_info()
    device = torch.device(device_info["device"])
    print(f"Device: {device_info['device']}, GPU: {device_info['gpu_name']}, VRAM: {device_info['vram_gb']} GB")

    # Load data
    train_loader, val_loader, num_labels = load_text_data(
        DATA_PATH, model_name=MODEL_NAME, batch_size=BATCH_SIZE,
    )

    # Create model
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=num_labels,
    )
    model = model.to(device)

    # Optimizer and scheduler
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=0.01)
    scheduler = ReduceLROnPlateau(optimizer, mode="min", patience=3, factor=0.5)

    # Mixed precision scaler
    scaler = torch.amp.GradScaler(device=device_info["device"])

    # Early stopping state
    best_val_loss = float("inf")
    patience_counter = 0
    best_metric = 0.0

    for epoch in range(MAX_EPOCHS):
        # --- Check time budget ---
        elapsed = time.time() - start
        if elapsed > TIME_BUDGET_SEC:
            print(f"Time budget exhausted at epoch {epoch} ({elapsed:.0f}s)")
            break

        # --- Training ---
        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for batch in train_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            optimizer.zero_grad()
            with torch.amp.autocast(device_type=device_info["device"]):
                outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
                logits = outputs.logits

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()

            train_loss += loss.item() * labels.size(0)
            preds = logits.argmax(dim=-1)
            train_correct += (preds == labels).sum().item()
            train_total += labels.size(0)

        avg_train_loss = train_loss / max(train_total, 1)

        # --- Validation ---
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch["input_ids"].to(device)
                attention_mask = batch["attention_mask"].to(device)
                labels = batch["labels"].to(device)

                with torch.amp.autocast(device_type=device_info["device"]):
                    outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
                    loss = outputs.loss
                    logits = outputs.logits

                val_loss += loss.item() * labels.size(0)
                preds = logits.argmax(dim=-1)
                val_correct += (preds == labels).sum().item()
                val_total += labels.size(0)

        avg_val_loss = val_loss / max(val_total, 1)
        val_accuracy = val_correct / max(val_total, 1)

        # Update scheduler
        scheduler.step(avg_val_loss)

        print(
            f"Epoch {epoch + 1}/{MAX_EPOCHS} - "
            f"Train Loss: {avg_train_loss:.4f} - "
            f"Val Loss: {avg_val_loss:.4f} - "
            f"Val Acc: {val_accuracy:.4f} - "
            f"LR: {optimizer.param_groups[0]['lr']:.2e}"
        )

        # --- Early stopping ---
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            best_metric = val_accuracy
            patience_counter = 0
            torch.save(model.state_dict(), "best_model.pt")
            print(f"  -> Saved best model (val_loss={best_val_loss:.4f})")
        else:
            patience_counter += 1
            if patience_counter >= PATIENCE:
                print(f"Early stopping at epoch {epoch + 1} (patience={PATIENCE})")
                break

    # --- Save predictions for diagnostics engine ---
    model.load_state_dict(torch.load("best_model.pt", weights_only=True))
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for batch in val_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)
            with torch.amp.autocast(device_type=device_info["device"]):
                outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                logits = outputs.logits
            preds = logits.argmax(dim=-1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    import pandas as pd
    pd.DataFrame({"y_true": all_labels, "y_pred": all_preds}).to_csv("predictions.csv", index=False)

    # --- Final result ---
    elapsed = time.time() - start
    result = {
        "metric_name": METRIC_NAME,
        "metric_value": best_metric,
        "best_val_loss": best_val_loss,
        "training_time_sec": round(elapsed, 1),
    }
    print(json.dumps(result))


if __name__ == "__main__":
    train()
